In [1]:
import pandas as pd

In [9]:
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]

#matrice bidimensionale

In [10]:
pd.DataFrame(mat)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [16]:
mat = pd.DataFrame([[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]])

In [18]:
mat.loc[2, 3]

13

In [24]:
import numpy as np
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14]] 
mat = np.array(mat)

mat[1, 3]

8

In [26]:
linear_data = np.array([x for x in range(27)])
print(linear_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [27]:
#il nuovo array ha 3 dimensioni, il codice specifica in ordine il numero di tabelle, poi righe e poi colonne
reshaped_data = linear_data.reshape((3, 3, 3))
print(reshaped_data)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [30]:
reshaped_data[0, 2, 2]

8

In [38]:
lunghezza_struttura = 28.75
rivetti = 15

In [39]:
#.linspace per creare punti/numeri linearmente spaziati
punti_inserimento_rivetti = np.linspace(0, lunghezza_struttura, rivetti)
print(punti_inserimento_rivetti)

[ 0.          2.05357143  4.10714286  6.16071429  8.21428571 10.26785714
 12.32142857 14.375      16.42857143 18.48214286 20.53571429 22.58928571
 24.64285714 26.69642857 28.75      ]


In [48]:
wine = pd.read_csv('wine.csv')

In [49]:
dim = wine.shape
print(dim)

(6497, 13)


In [57]:
wine.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality type  
0      9.4        5  red  
1      9.8        5  red  
2      9.8        5  red  
3      9.8        6  red  
4      9.4        5  red

In [72]:
wine.tail(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality   type  
6492     11.2        6  white  
6493      9.6        5  white  
6494      9.4        6  white  
6495     12.8        7  white  
6496     11.8        6  white

In [75]:
ultime_sei_colonne = pd.read_csv('wine.csv', usecols=range(7, 13))
print(ultime_sei_colonne)

      density    pH  sulphates  alcohol  quality   type
0     0.99780  3.51       0.56      9.4        5    red
1     0.99680  3.20       0.68      9.8        5    red
2     0.99700  3.26       0.65      9.8        5    red
3     0.99800  3.16       0.58      9.8        6    red
4     0.99780  3.51       0.56      9.4        5    red
...       ...   ...        ...      ...      ...    ...
6492  0.99114  3.27       0.50     11.2        6  white
6493  0.99490  3.15       0.46      9.6        5  white
6494  0.99254  2.99       0.46      9.4        6  white
6495  0.98869  3.34       0.38     12.8        7  white
6496  0.98941  3.26       0.32     11.8        6  white

[6497 rows x 6 columns]


In [76]:
wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378  
std       0.160787     0.148806     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [92]:
iris_data = pd.read_csv('iris.data')
print(iris_data.head(5))

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


In [93]:
#i nomi delle colonnenon descrivono cosa c'è nella colonna relativa
print(iris_data.columns)

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')


In [94]:
iris_data = pd.read_csv('iris.data', header=None, names=["sepal length in cm","sepal width in cm", "petal length in cm", "petal width in cm", "class"])


   sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa  


In [95]:
print(iris_data.head(5))

   sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa  


In [96]:
print(iris_data.tail(10))

     sepal length in cm  sepal width in cm  petal length in cm  \
140                 6.7                3.1                 5.6   
141                 6.9                3.1                 5.1   
142                 5.8                2.7                 5.1   
143                 6.8                3.2                 5.9   
144                 6.7                3.3                 5.7   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm           class  
140                2.4  Iris-virginica  
141                2.3  Iris-virginica  
142                1.9  Iris-virginica  
143                2.3  Iris-virginica  
144                2.5  Iris-virginica  
145                2.3  Iri

In [103]:
riepilogo= iris_data.describe()
print(riepilogo)

       sepal length in cm  sepal width in cm  petal length in cm  \
count          150.000000         150.000000          150.000000   
mean             5.843333           3.054000            3.758667   
std              0.828066           0.433594            1.764420   
min              4.300000           2.000000            1.000000   
25%              5.100000           2.800000            1.600000   
50%              5.800000           3.000000            4.350000   
75%              6.400000           3.300000            5.100000   
max              7.900000           4.400000            6.900000   

       petal width in cm  
count         150.000000  
mean            1.198667  
std             0.763161  
min             0.100000  
25%             0.300000  
50%             1.300000  
75%             1.800000  
max             2.500000  


In [104]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
print(fatturati_dict[1997])

12000


In [105]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))
fatturati_series[1997]

12000

In [111]:
import numpy as np

lista_di_liste = ([1, 1, 1, 1],
                 [5, 1, 1, 1],
                 [20, -4, 0, 42])
lista_di_liste = np.array(lista_di_liste)
print(lista_di_liste)

[[ 1  1  1  1]
 [ 5  1  1  1]
 [20 -4  0 42]]


In [114]:
import numpy as np

matrice_fantasiosa=np.array([[10, 22, 21, 8, 9],
                            [9, 42, 3, 18, 11],
                            [5, 4, 30, 12, 29],
                            [37, 31, 7, 2, 26],
                            [8, 6, 4, 33, 15]])


